### ISSUE TITLE
From句でエイリアスを使っていないとエラーになる

### ISSUE THREAD

**Issue by atsu0127** [atsu0127/SuperSQL#11]
## 概要
以下のクエリのようにエイリアスを使っていないとエラーが発生する
```
GENERATE HTML
cross_tab([store],, [floor]!, [name]!)
from dept;
```
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at supersql.dataconstructor.MakeSQL.makeMultipleSQL(MakeSQL.java:331)
	at supersql.dataconstructor.DataConstructor.getFromDB(DataConstructor.java:1155)
	at supersql.dataconstructor.DataConstructor.schemaToData(DataConstructor.java:359)
	at supersql.dataconstructor.DataConstructor.<init>(DataConstructor.java:246)
	at supersql.FrontEnd.execSuperSQL(FrontEnd.java:61)
	at supersql.FrontEnd.<init>(FrontEnd.java:32)
	at supersql.FrontEnd.main(FrontEnd.java:25)
```

**Comment by atsu0127** [comment]
#13で直したのでクローズします
